"""add phone parking to guests

Revision ID: 1565a6908c7f
Revises: 99a4460303d1
Create Date: 2026-05-26 09:25:49.369950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1565a6908c7f'
down_revision = '99a4460303d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=30), nullable=True, comment='Guest phone number'))
        batch_op.add_column(sa.Column('parking_required', sa.Boolean(), nullable=False,
                                      server_default=sa.text('false'),
                                      comment='True if the guest requires parking'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.drop_column('parking_required')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
