"""initial

Revision ID: 99a4460303d1
Revises: 
Create Date: 2026-05-26 09:08:19.764829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99a4460303d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_chat_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('guest_email', sa.String(length=255), nullable=False, comment='Email of the authenticated guest'),
    sa.Column('user_message', sa.Text(), nullable=False, comment='Verbatim message from the guest'),
    sa.Column('ai_response', sa.Text(), nullable=False, comment='Full response returned by gpt-4o-mini'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of this chat interaction'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guestbook_messages',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('guest_email', sa.String(length=255), nullable=False, comment='Email of the guest who wrote this message'),
    sa.Column('guest_name', sa.String(length=255), nullable=False, comment='Display name for this guestbook entry'),
    sa.Column('message', sa.Text(), nullable=False, comment='Guestbook message content'),
    sa.Column('ai_enhanced', sa.Boolean(), nullable=False, comment='True if guest accepted the AI-enhanced version of their message'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp when this message was posted'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guests',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('name', sa.String(length=255), nullable=True, comment="Guest's full name"),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Guest email — unique login identifier'),
    sa.Column('rsvp_status', sa.Enum('pending', 'attending', 'not_attending', name='rsvp_status_enum'), nullable=False, comment='RSVP status: pending | attending | not_attending'),
    sa.Column('meal_preference', sa.Enum('chicken', 'fish', 'vegetarian', 'vegan', name='meal_pref_enum'), nullable=True, comment='Meal preference: chicken | fish | vegetarian | vegan'),
    sa.Column('plus_one', sa.Boolean(), nullable=False, comment='True if guest is bringing a plus-one'),
    sa.Column('plus_one_name', sa.String(length=255), nullable=True, comment='Full name of the plus-one guest'),
    sa.Column('table_number', sa.Integer(), nullable=True, comment='Seating table number assigned by admin'),
    sa.Column('special_requests', sa.Text(), nullable=True, comment='Dietary restrictions, accessibility needs, etc.'),
    sa.Column('rsvp_submitted_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp of RSVP submission'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Record last-updated timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guests_email'), ['email'], unique=True)

    op.create_table('otp_tokens',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email address that requested the OTP'),
    sa.Column('otp_hash', sa.String(length=255), nullable=False, comment='SHA-256 hex digest of the plaintext OTP'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp when this OTP becomes invalid'),
    sa.Column('used', sa.Boolean(), nullable=False, comment='True if this OTP has already been used or invalidated'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp when this OTP was created'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_tokens_email'), ['email'], unique=False)

    op.create_table('photos',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key'),
    sa.Column('blob_url', sa.String(length=500), nullable=False, comment='Full Azure Blob Storage URL for this photo'),
    sa.Column('caption', sa.Text(), nullable=True, comment='Photo caption (may be AI-generated)'),
    sa.Column('uploaded_by', sa.String(length=255), nullable=False, comment='Email of the admin or guest who uploaded this photo'),
    sa.Column('display_order', sa.Integer(), nullable=False, comment='Display order in gallery (lower = earlier)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp when this photo was uploaded'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wedding_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-incrementing integer primary key'),
    sa.Column('key', sa.String(length=100), nullable=False, comment='Unique configuration key in snake_case'),
    sa.Column('value', sa.Text(), nullable=False, comment='String value for this configuration entry'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of the last update'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wedding_config')
    op.drop_table('photos')
    with op.batch_alter_table('otp_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_tokens_email'))

    op.drop_table('otp_tokens')
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guests_email'))

    op.drop_table('guests')
    op.drop_table('guestbook_messages')
    op.drop_table('ai_chat_logs')
    # ### end Alembic commands ###
